const chapters=[...document.querySelectorAll('.chapter')];const majorButtons=[...document.querySelectorAll('[data-major]')];const dots=[...document.querySelectorAll('.major-dot')];const wipe=document.querySelector('.wipe');let major=0,transitioning=false,wheelSum=0,wheelTimer,touchStart=null,lang;
try{lang=localStorage.getItem('portfolio-language')}catch(e){}lang=lang||(navigator.language.toLowerCase().startsWith('zh')?'zh':'en');
function setLang(next){lang=next;document.documentElement.lang=lang==='zh'?'zh-CN':'en';document.title=lang==='zh'?'曾逸帆 — Silicon to Intelligence':'Yifan Zeng — Silicon to Intelligence';document.querySelectorAll('[data-zh]').forEach(el=>el.textContent=el.dataset[lang]);document.querySelectorAll('[data-zh-html]').forEach(el=>el.innerHTML=el.dataset[lang+'Html']);const b=document.getElementById('lang');b.textContent=lang==='zh'?'EN':'中文';try{localStorage.setItem('portfolio-language',lang)}catch(e){}}
document.getElementById('lang').addEventListener('click',()=>setLang(lang==='zh'?'en':'zh'));setLang(lang);
function updateMajorUI(){dots.forEach((d,i)=>d.classList.toggle('active',i===major));document.querySelectorAll('.primary-nav [data-major]').forEach(b=>b.classList.toggle('active',Number(b.dataset.major)===major));history.replaceState(null,'','#'+chapters[major].id)}
function goMajor(next){next=Math.max(0,Math.min(chapters.length-1,next));if(next===major||transitioning)return;transitioning=true;const dir=next>major?'forward':'backward';wipe.className='wipe run '+dir;setTimeout(()=>{chapters[major].classList.remove('active');major=next;chapters[major].classList.add('active');chapters[major].querySelector('.chapter-scroll').scrollTop=0;updateMajorUI()},430);setTimeout(()=>{wipe.className='wipe';transitioning=false},970)}
majorButtons.forEach(b=>b.addEventListener('click',e=>{e.preventDefault();goMajor(Number(b.dataset.major))}));
function activeScroller(){return chapters[major].querySelector('.chapter-scroll')}
window.addEventListener('wheel',e=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const s=activeScroller(),atTop=s.scrollTop<=2,atBottom=s.scrollTop+s.clientHeight>=s.scrollHeight-2;if((e.deltaY>0&&atBottom)||(e.deltaY<0&&atTop)){e.preventDefault();wheelSum+=e.deltaY;clearTimeout(wheelTimer);wheelTimer=setTimeout(()=>wheelSum=0,180);if(Math.abs(wheelSum)>75){goMajor(major+(wheelSum>0?1:-1));wheelSum=0}}},{passive:false});
window.addEventListener('keydown',e=>{if(e.key==='ArrowDown'||e.key==='PageDown'){e.preventDefault();goMajor(major+1)}if(e.key==='ArrowUp'||e.key==='PageUp'){e.preventDefault();goMajor(major-1)}if(e.key==='ArrowRight')changeActiveSub(1);if(e.key==='ArrowLeft')changeActiveSub(-1)});
window.addEventListener('touchstart',e=>{const t=e.touches[0];touchStart={x:t.clientX,y:t.clientY}}, {passive:true});window.addEventListener('touchend',e=>{if(!touchStart)return;const t=e.changedTouches[0],dx=t.clientX-touchStart.x,dy=t.clientY-touchStart.y;if(Math.abs(dy)>70&&Math.abs(dy)>Math.abs(dx)){goMajor(major+(dy<0?1:-1))}else if(Math.abs(dx)>55){changeActiveSub(dx<0?1:-1)}touchStart=null},{passive:true});
function initSubsystem(root){const buttons=[...root.querySelectorAll('.subnav button')],panels=[...root.querySelectorAll('.subpanel')];root.dataset.current='0';buttons.forEach((b,i)=>b.addEventListener('click',()=>setSub(root,i)));root._buttons=buttons;root._panels=panels}
function setSub(root,next){const buttons=root._buttons,panels=root._panels,current=Number(root.dataset.current||0);next=Math.max(0,Math.min(panels.length-1,next));if(next===current)return;buttons[current].classList.remove('active');panels[current].classList.remove('active','enter-left','enter-right');buttons[next].classList.add('active');panels[next].classList.add('active',next>current?'enter-right':'enter-left');root.dataset.current=String(next);buttons[next].scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'})}
function changeActiveSub(delta){const root=chapters[major].querySelector('[data-subsystem]');if(!root)return;setSub(root,Number(root.dataset.current||0)+delta)}
document.querySelectorAll('[data-subsystem]').forEach(initSubsystem);
const hashIndex=chapters.findIndex(c=>'#'+c.id===location.hash);if(hashIndex>0){chapters[0].classList.remove('active');major=hashIndex;chapters[major].classList.add('active');updateMajorUI()}
